CREATE TABLE GUESTBOOK (
    MESSAGE_ID NUMBER(5,0), 
    GUEST_NAME VARCHAR2(20) DEFAULT null, 
    MESSAGE VARCHAR2(4000), 
    REGISTRY_DATE DATE DEFAULT null, 
    CONSTRAINT "GUESTBOOK_PK" PRIMARY KEY (MESSAGE_ID) 
);
commit;

CREATE SEQUENCE "GUEST_SEQ" 
MINVALUE 1 
MAXVALUE 99999 
INCREMENT BY 1 
START WITH 1 
NOCACHE 
NOORDER 
NOCYCLE;
